# Generated by Django 4.2.5 on 2023-09-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(unique=True, verbose_name='Телеграм ID пользователя')),
                ('phone', models.CharField(blank=True, max_length=12, verbose_name='Мобильный телефон')),
                ('firstname', models.CharField(blank=True, max_length=50, verbose_name='Имя пользователя')),
                ('lastname', models.CharField(blank=True, max_length=100, verbose_name='Фамилия пользователя')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='Телеграм username')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
        ),
    ]
